---
output: pdf_document
---

## 3. Methodology

In this section models were created trying to outperform the buy and hold strategy.
starting with the usage of the simplest models , different approaches were chosen to fulfill the goal.

### 3.1. Trading Signals

&nbsp;

Using signals to trade

in Section 2 we have learned different indicators and models for timeseries. these models and indicators are now used to trade the underlying asset. As an example we are taking the MA Crossings, as mentioned [2.3.3.](#GARCH) the points where the two MAs cross, are now used to create a trading signal. when the longer MA comes from below to the crossing we are going long the asset and if it approaches the point from above we're shorting the position. Technically we apply a 1 to a vector at each crossing, where we intend to buy and apply a -1 at the points we want to sell. 

### 3.2. using simple methods
#### 3.2.1. sma signals to trade 


```{r chap3.2 ma crossover, echo=FALSE, fig.cap="conversion data"}

load("data/data_mobi") 
n=20
# lentgths
n1=10
n2 =50
k=2

mobidat= data[,4] # chose the row and horizon
start="2015-10-30"
end="2020-04-30"


horizon=paste(start,"::",end,sep = "")


sma1 <-SMA(mobidat,n=n1)
sma2 <-SMA(mobidat,n=n2)


signal <-rep(0,length(sma1))

signal[which(sma1>sma2&lag(sma1)<lag(sma2))]<-1
signal[which(sma1<sma2&lag(sma1)>lag(sma2))]<--1

signal[which(sma1>sma2)]<-1
signal[which(sma1<sma2)]<--1

signal=reclass(signal,sma1)



chartSeries(mobidat,subset=horizon,theme=chartTheme("white"),name= "sna",type="")
addSMA(n=n1,on=1,col = "blue")
addSMA(n=n2,on=1,col = "red")
addTA(signal,type="S",col="red")


trade   =   Lag(signal[horizon],1)
return  =   diff(log(mobidat))
ret = return*trade

mean(ret,na.rm=T)
names(ret)="filter"

chart.Bar(ret,main="returns daily")
chart.CumReturns(ret, main="Naive Rule: Cum Returns")
chart.Drawdown(ret,main="Naive Rule: Percentage Drawdown")
charts.PerformanceSummary(ret, main="Naive Buy Rule")
```




