---
output: pdf_document
geometry: margin = 1in
---

## 6. Attachment


### 6.3.3. AR 

#### 6.3.3.1. Optimization code

&nbsp;

```{r, chap6.3.3.1 ,echo=T, eval=FALSE, include=T}
# AR-Optim####
performante_ar <- function(xin, xout) {
  # AR-Model Order p -> 1:8
  # Find best in-sample ar_obj
  # Compute out-of-of sample daily trading returns
  # Find best Sharpe
  best <- 0
  for (j in 1:8) {
    arma_obj <- arima(xin, order=c(j,0,0))
    mat_out <- cbind(xout)
    for (k in 1:(j)) {
      mat_out <- cbind(mat_out, lag(xout, k=k))
    }
    ar_pred <- arma_obj$coef[length(arma_obj$coef)] +
      as.matrix(mat_out[,2:ncol(mat_out)])%*%arma_obj$coef[1:(length(arma_obj$coef)-1)]
    
    ret_arima <- na.exclude(sign(ar_pred)*xout)
    
    sharpe_ar <- as.double(sqrt(250) * mean(ret_arima, na.rm=T) / sqrt(var(ret_arima, na.rm=T)))
    
    if (sharpe_ar > best) {
      best <- as.data.frame(sharpe_ar)
      rownames(best) <- paste(j)
    }
  }
  return(list(sharpe_ar=best, ar_p=rownames(best)))
}
perfplot_ar <- function(optim_ar_obj, lr_series, inx, insamp="2019-01-01") {
  # Max Optim-Element
  max_obj <- optim_ar_obj[which.max(optim_ar_obj[,2]),]
  
  
  # Startdate
  start_date <- optim_ar_obj[which.max(optim_ar_obj[,2]),][1]
  
  xall <- lr_series[paste(start_date,"/",sep="")][,inx]
  xin <- xall[paste("/",insamp,sep="")]
  xout <- xall[paste(insamp,"/",sep="")]
  
  
  # sharpe
  sharpe_bnh <- as.double(sqrt(250) * mean(xout) / sqrt(var(xout)))
  sharpe_ar <- as.numeric(optim_ar_obj[which.max(optim_ar_obj[,2]),][2])
  
  # Model Order AR(p)
  p <- as.numeric(optim_ar_obj[which.max(optim_ar_obj[,2]),][3])
  
  # AR-Fit, in-sample
  arma_obj <- arima(xin, order=c(p,0,0))
  
  # AR-Pred, out-of-sample
  mat_out <- cbind(xout)
  for (k in 1:(p)) {
    mat_out <- cbind(mat_out, lag(xout, k=k))
  }
  ar_pred <- arma_obj$coef[length(arma_obj$coef)] +
    as.matrix(mat_out[,2:ncol(mat_out)])%*%arma_obj$coef[1:(length(arma_obj$coef)-1)]
  
  # AR-Returns
  ret_arima <- sign(ar_pred)*xout
  
  # Plot
  perf_bnh <- cumsum(xout)
  perf_ar <- cumsum(na.exclude(ret_arima))
  ymin <- min(c(min(perf_bnh), min(perf_ar)))
  ymax <- max(c(max(perf_bnh), max(perf_ar)))

  plot(perf_bnh, main=paste("Startdate: ",start_date,"| Out-of-sample-Index: ",inx), lwd=1.5,
       ylim=c(ymin-0.1*abs(ymin), ymax+0.1*ymax))
  lines(perf_ar, lty=2, lwd=1, col="red")
  print(addLegend("topleft", legend.names = c(paste("Buy & Hold:", round(sharpe_bnh, 2)),
                                              paste("AR(",p,"):", round(sharpe_ar, 2))),
                  lty=c(1, 2),
                  lwd=c(1.5, 1),
                  col=c("black", "red"),
                  cex=0.8))
}
optim_ar <- function(x.lr, inx, insamp="2019-01-01", minyear=3, maxyear=18) {
  ind.lr <- x.lr
  year_list <- NULL
  for (yx in minyear:maxyear) {
    year_list <- c(year_list, paste(2000+yx,"-01-01", sep=""))
  }
  
  # Create result_matrix
  res_mat <- matrix(1:(3*length(year_list)), ncol=3,
                    dimnames = list(1:length(year_list), c("StartDate", "AR-Sharpe", "p")))
  
  
  pb <- txtProgressBar(min = 1, max = length(year_list), style = 3)
  
  # Loop through years
  for (i in 1:length(year_list)) {
    startdate <- year_list[i]
    
    ind.lr.all <- ind.lr[paste(startdate,"/",sep="")]
    ind.lr.in <- ind.lr.all[paste("/",insamp,sep="")]
    ind.lr.out <- ind.lr.all[paste(insamp,"/",sep="")]
    
    yolo1 <- performante_ar(xin=ind.lr.in[,inx], xout=ind.lr.out[,inx])
    
    res_mat[i,1] <- year_list[i]
    res_mat[i,2:3] <- c(round(as.numeric(yolo1$sharpe_ar), 3), round(as.numeric(yolo1$ar_p)))
    
    setTxtProgressBar(pb, i)
  }
  res_df <- as.data.frame(res_mat)
  close(pb)
  
  # print(head(ind.lr.all))
  # print(tail(ind.lr.all))
  perfplot_ar(res_df, ind.lr, inx)
  
  return(res_df)
}
```

\newpage

### 6.3.4. Single Ma

#### 6.3.4.1. Optimization code

&nbsp;

```{r, chap6.3.4.1 ,echo=T, eval=FALSE, include=T}
loop_sma <- function(x=ind.lr, inx=1, insamp = "2019-01-01", minyear=3, maxyear=16) {
  
  year_list <- NULL
  for (yx in minyear:maxyear) {
    year_list <- c(year_list, paste(2000+yx,"-01-01", sep=""))
  }
  
  # Create result_matrix
  res_mat <- matrix(1:(7*length(year_list)), ncol=7,
                    dimnames = list(1:length(year_list), c("StartDate", "Sharpe", "L_Sharpe", "Drawdown", "L_Drawdown", "MSE", "L_MSE")))
  
  lirino <- NULL
  
  pb <- txtProgressBar(min = 1, max = length(year_list), style = 3)
  
  # Loop through years
  for (i in 1:length(year_list)) {
    startdate <- year_list[i]
    
    
    opt_obj <- optimize_sma(x, inx, min_L=5, max_L=500, L_forecast=1, start = startdate, insamp = "2019-01-01", plot_T=FALSE)
    res_mat[i,] <- c(year_list[i],
                     as.numeric(opt_obj$sharpe_opt), rownames(opt_obj$sharpe_opt),
                     as.numeric(opt_obj$draw_opt), rownames(opt_obj$draw_opt),
                     as.numeric(opt_obj$mse_opt), rownames(opt_obj$mse_opt))
    
    
    resulterino <- opt_obj$res_mat
    StartDate <- rep(year_list[i], dim(resulterino)[1])
    result <- as.data.frame(cbind(resulterino, StartDate))
    
    lirino <- rbind(lirino, result)
    
    
    setTxtProgressBar(pb, i)
  }
  res_df <- as.data.frame(res_mat)
  close(pb)
  
  return(list(res_df=res_df, lirino=lirino))  
}
optimize_sma_opt <- function(x, inx, min_L=5, max_L=500, L_forecast=1, start = "2015-10-30", insamp = "2019-01-01") {
  
  xall <- x[paste(start,"/",sep="")][,inx]
  xin <- xall[paste("/",insamp,sep="")]
  xout <- xall[paste(insamp,"/",sep="")]
  
  sharpe_opt<- -9.e+99
  draw_opt <- -9.e+99
  mse_opt <- -9.e+99
  
  filler <- 1
  res_mat <- matrix(1:((length(min_L:max_L))*4), ncol=4,
                    dimnames = list(1:(length(min_L:max_L)), c("L", "Sharpe", "Drawdown", "MSE")))
  
  pb <- txtProgressBar(min = min_L, max = max_L, style = 3)
  
  for (L in min_L:max_L) {
    # Moving Average
    yhat_full <- SMA(xin, n=L)
    # Cut init
    yhat <- yhat_full[max_L:length(yhat_full)]
    
    # Perf (daily)
    perf <- lag(sign(yhat))*xin
    
    sharpe <- sqrt(250)*mean(perf,na.rm=T)/sqrt(var(perf,na.rm=T))
    
    maxdraw<- -max(abs(Drawdowns(na.exclude(perf), geometric = F)))
    
    future_returns <- lag(SMA(xin, n=L_forecast), k=-L_forecast)
    MSE <- -as.double(mean((future_returns-yhat)^2, na.rm=T))/var(xin, na.rm=T)
    
    res_mat[filler,] <- c(L, sharpe, maxdraw, MSE)
    
    filler <- filler + 1
    
    # Best
    if (sharpe > sharpe_opt) {
      sharpe <- as.data.frame(sharpe)
      sharpe_opt <- sharpe
      rownames(sharpe_opt) <- paste(L)
      colnames(sharpe_opt) <- "Sharpe"
    }
    
    if (maxdraw > draw_opt) {
      maxdraw <- as.data.frame(maxdraw)
      draw_opt <- maxdraw
      rownames(draw_opt) <- paste(L)
      colnames(draw_opt) <- "Drawdown"
    }
    
    if (MSE > mse_opt) {
      MSE <- as.data.frame(MSE)
      mse_opt <- MSE
      rownames(mse_opt) <- paste(L)
      colnames(mse_opt) <- "MSE"
    }
    
    setTxtProgressBar(pb, L)
  }
  close(pb)
  
  listerino <- list(sharpe_opt=sharpe_opt, draw_opt=draw_opt, mse_opt=mse_opt, res_mat=res_mat)
  return(listerino)
}

perfplot_sma_opt <- function(xall, insamp, res_obj, inx) {
  xall <- xall[,inx]
  
  # Optima
  sharpe_opt <- res_obj$res_df[which.max(res_obj$res_df[,2]),1:3]
  drawdown_opt <- res_obj$res_df[which.max(res_obj$res_df[,4]),c(1,4:5)]
  mse_opt <- res_obj$res_df[which.max(res_obj$res_df[,6]),c(1,6:7)]
  
  # Filterlengths
  sharpe_L <- as.numeric(sharpe_opt[3])
  drawdown_L <- as.numeric(drawdown_opt[3])
  MSE_L <- as.numeric(mse_opt[3])
  
  # Startdates
  sharpe_startdate <- sharpe_opt[1]
  
  # Trading Signal
  sharpe_signal <- sign(SMA(xall, n=sharpe_L))
  drawdown_signal <- sign(SMA(xall, n=drawdown_L))
  MSE_signal <- sign(SMA(xall, n=MSE_L))
  
  # Returns
  sharpe_ret <- lag(sharpe_signal)*xall
  drawdown_ret <- lag(drawdown_signal)*xall
  MSE_ret <- lag(MSE_signal)*xall
  
  bnh_perf <- cumsum(na.exclude(xall[paste(insamp, "/", sep=""),]))
  sharpe_perf <- cumsum(na.exclude(sharpe_ret[paste(insamp, "/", sep=""),]))
  drawdown_perf <- cumsum(na.exclude(drawdown_ret[paste(insamp, "/", sep=""),]))
  MSE_perf <- cumsum(na.exclude(MSE_ret[paste(insamp, "/", sep=""),]))
  
  ymin <- min(c(min(bnh_perf), min(sharpe_perf), min(drawdown_perf), min(MSE_perf)))
  ymax <- max(c(max(bnh_perf), max(sharpe_perf), max(drawdown_perf), max(MSE_perf)))
  
  
  plot(bnh_perf, main=paste("Out-of-sample-Index: ",inx), lwd=2,
       ylim=c(ymin-0.1*abs(ymin), ymax+0.1*ymax))
  lines(sharpe_perf, col="#DF536B", lty=2, lwd=2)
  lines(drawdown_perf, col="#2297E6", lty=3, lwd=2)
  lines(MSE_perf, col="#61D04F", lty=4, lwd=2)
  
  addLegend("topleft", legend.names = c("Buy & Hold",
                                        paste("StartDate: ", sharpe_opt[1], "| Sharpe | L: ",sharpe_L),
                                        paste("StartDate: ", drawdown_opt[1], "| Drawdown | L: ",drawdown_L),
                                        paste("StartDate: ", mse_opt[1], "| MSE | L: ",MSE_L)),
            lty=c(1, 2, 3, 4),
            lwd=c(2, 2, 2, 2),
            col=c("#000000", "#DF536B", "#2297E6", "#61D04F"),
            cex=0.8)
  
  lines(sharpe_signal, on=NA, ylim=c(-1.5, 1.5), col="#DF536B", lwd=2)
  lines(drawdown_signal, on=NA, ylim=c(-1.5, 1.5), col="#2297E6", lwd=2)
  print(lines(MSE_signal, on=NA, ylim=c(-1.5, 1.5), col="#61D04F", lwd=2))
}

loop_sma_trading <- function(x, inx, min_L=5, max_L=500, insamp = "2018-12-31", invest_amount=1000000, tradingcosts=190) {
  
  
  filler <- 1
  res_mat <- matrix(1:((length(min_L:max_L))*4), ncol=4,
                    dimnames = list(1:(length(min_L:max_L)), c("L", "SMA-Return", "Trades", "Sharpe")))
  
  pb <- txtProgressBar(min = min_L, max = max_L, style = 3)
  
  for (L in min_L:max_L) {
    # SMA L<-328
    sma_full <- SMA(x[,inx], n=L)
    
    # Cut init
    sma_cut <- sma_full[paste(insamp, "/", sep="")]
    
    # Perf (daily)
    perf <- lag(sign(sma_cut))*x[,inx][paste(insamp, "/", sep="")]
    trade_sig <- lag(sign(sma_cut))
    
    # Count Trades
    sma_trade_count <- trading_counter(as.numeric(na.exclude(trade_sig)))
    
    # Sharpe
    sharpe <- sharpe_fun(na.exclude(perf))
    
    sma_ret <- tail((cumsum(na.exclude(perf)) * invest_amount) - (sma_trade_count * tradingcosts), 1)
    bnh_ret <- cumsum(x[,inx][paste(insamp, "/", sep="")]) * invest_amount
    
    
    res_mat[filler,] <- c(L, sma_ret, sma_trade_count, sharpe)
    
    filler <- filler + 1
    
    setTxtProgressBar(pb, L)
  }
  close(pb)
  res_df <- as.data.frame(res_mat)
  return(res_df)
}

plot_sma <- function(x, inx, L, insamp = "2018-12-31") {
  sma_full <- SMA(x[,inx], n=L)
  
  # Cut init
  sma_cut <- sma_full[paste(insamp, "/", sep="")]
  
  # Perf (daily)
  perf <- lag(sign(sma_cut))*x[,inx][paste(insamp, "/", sep="")]
  trade_sig <- lag(sign(sma_cut))
  
  # Trade Counter
  sma_trade_count <- trading_counter(as.numeric(na.exclude(trade_sig)))
  
  # Sharpe
  bnh_sharpe <- round(sharpe_fun(x[,inx]["2019-01-01/"]), 3)
  trade_sharpe <- round(sharpe_fun(na.exclude(perf)), 3)
  
  bnh_perf <- cumsum(x[,inx]["2019-01-01/"])
  trade_perf <- cumsum(na.exclude(perf))
  
  ymin <- min(c(min(bnh_perf), min(trade_perf)))
  ymax <- max(c(max(bnh_perf), max(trade_perf)))
  
  plot(bnh_perf, main=paste("Out-of-sample-Index: ",inx), lwd=2,
       ylim=c(ymin-0.1*abs(ymin), ymax+0.1*ymax))
  lines(trade_perf, col="#E413A3", lty=2, lwd=2)

  
  addLegend("topleft", legend.names = c(paste("Buy & Hold | Sharpe=", bnh_sharpe),
                                        paste("Trading-Opt.=",trade_sharpe, "| L=",L, "| Trades n=", sma_trade_count)),
            lty=c(1, 2),
            lwd=c(2, 2),
            col=c("#000000", "#E413A3"),
            cex=0.8)
  
  print(lines(trade_sig, on=NA, ylim=c(-1.5, 1.5), col="#E413A3", lwd=2))
}
```

\newpage

#### 6.3.4.2. Plots & Tables {#sma-appendix}

&nbsp;

```{r, chap6.3.4.1, echo=FALSE, fig.cap="Optim", fig.dim=c(11, 6), out.width = "100%", fig.keep = 'last'}
load("data/R_Files/optim_sma_2.RData")
seper <- (500-5)+1
x_s <- res2$res_df[,3] + 1 + (0:13*seper)
y_s <- res2$res_df[,2]

x_d <- res2$res_df[,5] + 1 + (0:13*seper)
y_d <- res2$res_df[,4]

x_m <- res2$res_df[,7] + 1 + (0:13*seper)
y_m <- res2$res_df[,6]

plot(x=1:length(res2$lirino[,2]), y=res2$lirino[,2], type="l", col="#DF536B", main="Performance Indicators | SMA | Index 2", xlab = "L", ylab="", xaxt = "n", ylim=c(-2, 2))
axis(1, at=c(1, seper, 1+2*seper, 2*seper+seper), labels=c("5", "500", "5", "500"))
axis(3, at=c(1+seper, seper+seper), labels=c("5", "500"))
axis(4, at=c(-1.5, -0.5, 0.5, 1.5), labels=c("-0.15", "-0.10", "-0.05", "0"))

abline(v=1, lty=2, col="black")
abline(v=1+(500-5), lty=2, col="black")
abline(h=1.5, lty=2, col="black")
abline(h=0, lty=2, col="black")

lines((res2$lirino[,3])*18.65+1.5, type="l", col="#2297E6", lty=1)
lines(res2$lirino[,4], type="l", col="#61D04F")

points(x_s, y_s, pch=19, col="#DF536B")
points(x_d, y_d*18.65+1.5, pch=19, col="#2297E6")
points(x_m, y_m, pch=19, col="#61D04F")

legend("topleft", legend=c("Sharpe", "MSE"),
       col=c("#DF536B", "#61D04F"), lty=c(1,1), cex=0.8,
       bty = "n")

legend("topright", legend="Drawdown",
       col="#2297E6", lty=1, cex=0.8,
       bty = "n")
for (i in 0:13) {
  text((1+500-5)/2 + seper*i, -2, paste(2003+i, "-01-01", sep=""), cex=0.6)
}
```


```{r tab6.1, echo=FALSE}
tab2 <- res2$res_df
tab2$Sharpe <- round(tab2$Sharpe, 2)
tab2$Drawdown <- round(tab2$Drawdown, 6)
tab2$MSE <- round(tab2$MSE, 3)
kbl(tab2, caption="SMA-Optima by performance indicators | Index 2", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("striped", "hold_position")) %>%
  # column_spec(2:3, color="#DF536B") %>%
  # column_spec(4:5, color="#2297E6") %>%
  # column_spec(6:7, color="#61D04F")
  column_spec(2:3, color = "#DF536B",
              background = c(rep("#FFFFFF", 13), "#F4DBDF")) %>%
    column_spec(6:7, color = "#61D04F",
              background = c(rep("#FFFFFF", 5), "#C2EABC", rep("#FFFFFF", 8))) %>%
  column_spec(4:5, color = "#2297E6",
              background = c(rep("#FFFFFF", 13), "#C2DFF5"))
```

\newpage

```{r, chap6.3.4.2, echo=FALSE, fig.cap="Best", fig.dim=c(11, 6), out.width = "100%"}
perfplot_sma_opt(xall=log_ret_ind, insamp="2019-01-01", res_obj=res2, inx=2)
```

\newpage

```{r, chap6.3.4.3, echo=FALSE, fig.cap="Optim", fig.dim=c(11, 6), out.width = "100%", fig.keep = 'last'}
load("data/R_Files/optim_sma_3.RData")
seper <- (500-5)+1
x_s <- res3$res_df[,3] + 1 + (0:13*seper)
y_s <- res3$res_df[,2]

x_d <- res3$res_df[,5] + 1 + (0:13*seper)
y_d <- res3$res_df[,4]

x_m <- res3$res_df[,7] + 1 + (0:13*seper)
y_m <- res3$res_df[,6]

plot(x=1:length(res3$lirino[,2]), y=res3$lirino[,2], type="l", col="#DF536B", main="Performance Indicators | SMA | Index 3", xlab = "L", ylab="", xaxt = "n", ylim=c(-2.5, 2))
axis(1, at=c(1, seper, 1+2*seper, 2*seper+seper), labels=c("5", "500", "5", "500"))
axis(3, at=c(1+seper, seper+seper), labels=c("5", "500"))
axis(4, at=c(0.5, -0.25, -1), labels=c("0", "-0.15", "-0.3"))

abline(v=1, lty=2, col="black")
abline(v=1+(500-5), lty=2, col="black")
abline(h=0.5, lty=2, col="black")
abline(h=0, lty=2, col="black")

lines((res3$lirino[,3])*4.92+0.5, type="l", col="#2297E6", lty=1)
lines(res3$lirino[,4], type="l", col="#61D04F")

points(x_s, y_s, pch=19, col="#DF536B")
points(x_d, y_d*4.92+0.5, pch=19, col="#2297E6")
points(x_m, y_m, pch=19, col="#61D04F")

legend("topleft", legend=c("Sharpe", "MSE"),
       col=c("#DF536B", "#61D04F"), lty=c(1,1), cex=0.8,
       bty = "n")

legend("topright", legend="Drawdown",
       col="#2297E6", lty=1, cex=0.8,
       bty = "n")
for (i in 0:13) {
  text((1+500-5)/2 + seper*i, -2.5, paste(2003+i, "-01-01", sep=""), cex=0.6)
}
```


```{r tab6.2, echo=FALSE}
tab3 <- res3$res_df
tab3$Sharpe <- round(tab3$Sharpe, 2)
tab3$Drawdown <- round(tab3$Drawdown, 6)
tab3$MSE <- round(tab3$MSE, 3)
kbl(tab3, caption="SMA-Optima by performance indicators | Index 3", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("hold_position")) %>%
  # column_spec(2:3, color="#DF536B") %>%
  # column_spec(4:5, color="#2297E6") %>%
  # column_spec(6:7, color="#61D04F")
  column_spec(2:3, color = "#DF536B",
              background = c(rep("#FFFFFF", 13), "#F4DBDF")) %>%
  column_spec(6:7, color = "#61D04F",
              background = c(rep("#FFFFFF", 12), "#C2EABC", "#FFFFFF")) %>%
  column_spec(4:5, color = "#2297E6",
              background = c(rep("#FFFFFF", 13), "#C2DFF5"))
```

\newpage

```{r, chap6.3.4.4, echo=FALSE, fig.cap="Best", fig.dim=c(11, 6), out.width = "100%", fig.keep = 'last'}
perfplot_sma_opt(xall=log_ret_ind, insamp="2019-01-01", res_obj=res3, inx=3)
```

\newpage

```{r, chap6.3.4.5, echo=FALSE, fig.cap="Optim", fig.dim=c(11, 6), out.width = "100%"}
load("data/R_Files/optim_sma_4.RData")
seper <- (500-5)+1
x_s <- res4$res_df[,3] + 1 + (0:13*seper)
y_s <- res4$res_df[,2]

x_d <- res4$res_df[,5] + 1 + (0:13*seper)
y_d <- res4$res_df[,4]

x_m <- res4$res_df[,7] + 1 + (0:13*seper)
y_m <- res4$res_df[,6]

plot(x=1:length(res4$lirino[,2]), y=res4$lirino[,2], type="l", col="#DF536B", main="Performance Indicators | SMA | Index 4", xlab = "L", ylab="", xaxt = "n", ylim=c(-3, 2))
axis(1, at=c(1, seper, 1+2*seper, 2*seper+seper), labels=c("5", "500", "5", "500"))
axis(3, at=c(1+seper, seper+seper), labels=c("5", "500"))
axis(4, at=c(0.5, 0, -0.5, -1, -1.5), labels=c("0", "-0.1", "-0.2", "-0.3", "-0.4"))

abline(v=1, lty=2, col="black")
abline(v=1+(500-5), lty=2, col="black")
abline(h=0.5, lty=2, col="black")
abline(h=0, lty=2, col="black")

lines((res4$lirino[,3])*5+0.5, type="l", col="#2297E6", lty=1)
lines(res4$lirino[,4], type="l", col="#61D04F")

points(x_s, y_s, pch=19, col="#DF536B")
points(x_d, y_d*5+0.5, pch=19, col="#2297E6")
points(x_m, y_m, pch=19, col="#61D04F")

legend("topleft", legend=c("Sharpe", "MSE"),
       col=c("#DF536B", "#61D04F"), lty=c(1,1), cex=0.8,
       bty = "n")

legend("topright", legend="Drawdown",
       col="#2297E6", lty=1, cex=0.8,
       bty = "n")
for (i in 0:13) {
  text((1+500-5)/2 + seper*i, -3, paste(2003+i, "-01-01", sep=""), cex=0.6)
}
```


```{r tab6.3, echo=FALSE}
tab4 <- res4$res_df
tab4$Sharpe <- round(tab4$Sharpe, 2)
tab4$Drawdown <- round(tab4$Drawdown, 6)
tab4$MSE <- round(tab4$MSE, 3)
kbl(tab4, caption="SMA-Optima by performance indicators | Index 4", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("hold_position")) %>%
  # column_spec(2:3, color="#DF536B") %>%
  # column_spec(4:5, color="#2297E6") %>%
  # column_spec(6:7, color="#61D04F")
  column_spec(2:3, color = "#DF536B",
              background = c(rep("#FFFFFF", 13), "#F4DBDF")) %>%
  column_spec(4:5, color = "#2297E6",
              background = c(rep("#FFFFFF", 13), "#C2DFF5")) %>%
  column_spec(6:7, color = "#61D04F",
              background = c(rep("#FFFFFF", 12), "#C2EABC", "#FFFFFF"))
```

\newpage

```{r, chap6.3.4.6, echo=FALSE, fig.cap="Best", fig.dim=c(11, 6), out.width = "100%"}
perfplot_sma_opt(xall=log_ret_ind, insamp="2019-01-01", res_obj=res4, inx=4)
```
\newpage
### 6.3.5. Best ma crossings

#### 6.3.5.1. Optimization code {#optimizationmacross}

&nbsp;

```{r, chap6.3.5.1, echo=T, eval=FALSE,include=T}
loop_func_v3 <- function(data, minyear=3, maxyear=18,returnmax=10){
  #This function uses the cross_optim_easy_v2 function an loops the function through the insample timespan and returns a data    frame 
  
  year_list <- NULL
  for (year in minyear:maxyear) {
    year_list <- c(year_list, paste(2000+year,"-01-01", sep=""))
  }
  
  pb <- txtProgressBar(min = 1, max = length(year_list), style = 3)
  startdate=as.Date(paste(2000+minyear,"-01-01", sep=""))
  
  datevec <- as.data.frame(c(rep(startdate,returnmax)))
  colnames(datevec)="startdate"
  iteration<- cross_optim_easy_v3(x=data, start=startdate,returnmax=returnmax)
  iteration_withdate=cbind(datevec,iteration)
  
  # Loop through years
  for (i in 2:length(year_list)) {
    startdate <- year_list[i]
    iteration<- cross_optim_easy_v3(x=data, start=startdate,returnmax=returnmax)
    
    datevec <- as.data.frame(c(rep(as.Date(startdate),returnmax)))
    colnames(datevec)="startdate"
    
    iteration_withdate_loop=cbind(datevec,iteration)
    iteration_withdate=rbind(iteration_withdate,iteration_withdate_loop)
    
    setTxtProgressBar(pb, i)
  }
  close(pb)
  iteration_withdate <- xts(iteration_withdate[,-1], iteration_withdate[,1])
  return(iteration_withdate)
}
cross_optim_easy_v3 <- function(x, start, end = "2018-12-31", L1min = 1, L1max = 50, L2min =  100, L2max = 250,returnmax=10){ 
  ###This function optimizes the ma crossings with the given filterlength in the given timespan and returns a dataframe with the  "returnmax"
  # sharpe and drawdownfilter which where found by common trading rules of ma crossings.
  horizon <- paste(start,"::",end,sep = "")
  
  sharpmat<-matrix(NA,L1max,L2max)  ## creating empty matrizes for sharpe and maxdrawdown
  drawmat <-matrix(NA,L1max,L2max)
  
  pb = txtProgressBar(min = L1min, max = L1max, style = 3)
  for (k in L1min:L1max)
  {
    
    for (j in L2min:L2max)
    {
      
      # Simple Moving Averages
      sma1 <- SMA(x,k)
      sma2 <- SMA(x,j)
      
      # Signals
      signal <- rep(0,length(sma1))
      signal[which(sma1>sma2&lag(sma1)<lag(sma2))] <- 1
      signal[which(sma1<sma2&lag(sma1)>lag(sma2))]< - -1
      signal[which(sma1>sma2)] <- 1
      signal[which(sma1<sma2)] <- -1
      signal <- reclass(signal,sma1)
      
      # Trading
      trade   <-   Lag(signal[horizon],1)
      return  <-   diff(log(x))
      ret <- return*trade
      ret <- na.exclude(ret)
      
      # Sharpe
      sharpmat[k,j] <- sqrt(250)*mean(ret)/sqrt(var(ret))
      
      # Drawdown
      drawmat[k,j] <- -max(abs(Drawdowns(ret, geometric = F)))
    }
    setTxtProgressBar(pb, k)
  }
  close(pb)
  
  #finding the [returmax] best sharpevalues an thei indexes =l1 / l2
  sharpmax <- which(sharpmat>=sort(sharpmat, decreasing = T)[returnmax], arr.ind = T)
  sharpmax=head(sharpmax,returnmax)  
  #finding the [returmax] best drawevalues an thei indexes =l1 / l2
  drawmax <- which(drawmat>=sort(drawmat, decreasing = T)[returnmax], arr.ind = T)
  drawmax=head(drawmax,returnmax)  
  
  maximus=cbind(sharpmat[sharpmax],sharpmax,drawmat[drawmax],drawmax)    #combining the vector to return each value
  colnames(maximus)=c("sharpe","sharpe_l1","sharpe_l2","drawdown","drawdown_l1","drawdown_l2")
  return(as.data.frame(maximus))
}
```
\newpage

#### 6.3.5.2. Plots & Tables

&nbsp;

```{r macrosstable index 1, echo=FALSE}
index_1_onebest_year=as.data.frame(index_1_onebest_year)
index_1_onebest_year[,c(1,4)]=round(index_1_onebest_year[,c(1,4)],3)
kbl(index_1_onebest_year, caption="index 1 best", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```
```{r macrosstable index 2, echo=FALSE}
index_2_onebest_year=as.data.frame(index_2_onebest_year)
index_2_onebest_year[,c(1,4)]=round(index_2_onebest_year[,c(1,4)],3)
kbl(index_2_onebest_year, caption="index 2 best", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```
\newpage
```{r macrosstable index 3, echo=FALSE}
index_3_onebest_year=as.data.frame(index_3_onebest_year)
index_3_onebest_year[,c(1,4)]=round(index_3_onebest_year[,c(1,4)],3)
kbl(index_3_onebest_year, caption="index 3 best", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```
```{r macrosstable index 4, echo=FALSE}
index_4_onebest_year=as.data.frame(index_4_onebest_year)
index_4_onebest_year[,c(1,4)]=round(index_4_onebest_year[,c(1,4)],3)
kbl(index_4_onebest_year, caption="index 4 best", booktabs = T, linesep = "") %>%
  kable_styling(latex_options = c("striped", "hold_position"))
```
\newpage
```{r, chap3.2.4.1.8, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 2", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
##################sharpe maxdrow 10
plot(index_2_tenbest_year[,1],ylim= c(-5,4),main= "Max Sharpe/Drawdown 10 best Hyperoptimization Index 2",col="black",type="p",major.ticks="auto",format.labels="%b-%Y")
lines(index_2_tenbest_year[,4]*100,lwd=2,col="green",type="p")
addLegend("topleft", on=1, legend.names = c("Sharpe ", "MaxDrawdown * 100 "), lty=c(1, 1), lwd=c(2, 2),col=c("black","green"))

```
```{r, chap3.2.4.1.9, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 2", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
################## lengths
plot(index_2_tenbest_year[,2],type="p",col= "red",main= "Filterlengths 10 best Hyperoptimization Index 2 ",ylim=c(-10,260),format.labels="%b-%Y")
lines(index_2_tenbest_year[,3], col=c("coral"),lwd=2,type="p")
lines(index_2_tenbest_year[,5], col=c("blue"),lwd=2,type="p")
lines(index_2_tenbest_year[,6], col=c("cornflowerblue"),lwd=2,type="p")
lines(index_1_onebest_year[,c(2,3,5,6)],type="p",pch=3,lwd= 3,cex=2 ,col= c("red","coral","blue","cornflowerblue"))

addLegend("left", on=1, legend.names = c("long filter sharpe", "long filter drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("coral","cornflowerblue"))
addLegend("bottomleft", on=1, legend.names = c("short filter sharpe", "short filter Drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("red","blue"))
<<<<<<< HEAD
addLegend("topright", on=1, legend.names = c("maximum values"), pch=3,col="black")
=======
>>>>>>> main

```
\newpage
```{r, chap3.2.4.1.10, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 3", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
##################sharpe maxdrow 10
plot(index_3_tenbest_year[,1],ylim= c(-7,4),main= "Max Sharpe/Drawdown 10 best Hyperoptimization Index 3",col="black",type="p",major.ticks="auto",format.labels="%b-%Y")
lines(index_3_tenbest_year[,4]*100,lwd=2,col="green",type="p")
addLegend("topleft", on=1, legend.names = c("Sharpe ", "MaxDrawdown * 100 "), lty=c(1, 1), lwd=c(2, 2),col=c("black","green"))

```
```{r, chap3.2.4.1.11, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 3", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
################## lengths
plot(index_3_tenbest_year[,2],type="p",col= "red",main= "Filterlengths 10 best Hyperoptimization Index 3 ",ylim=c(-10,260),format.labels="%b-%Y")
lines(index_3_tenbest_year[,3], col=c("coral"),lwd=2,type="p")
lines(index_3_tenbest_year[,5], col=c("blue"),lwd=2,type="p")
lines(index_3_tenbest_year[,6], col=c("cornflowerblue"),lwd=2,type="p")
lines(index_3_onebest_year[,c(2,3,5,6)],type="p",pch=3,lwd= 3,cex=2 ,col= c("red","coral","blue","cornflowerblue"))

addLegend("left", on=1, legend.names = c("long filter sharpe", "long filter drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("coral","cornflowerblue"))
addLegend("bottomleft", on=1, legend.names = c("short filter sharpe", "short filter Drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("red","blue"))
addLegend("topright", on=1, legend.names = c("maximum values"), pch=3,col="black")

```
\newpage
```{r, chap3.2.4.1.12, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 4", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
##################sharpe maxdrow 10
plot(index_4_tenbest_year[,1],ylim= c(-2,4),main= "Max Sharpe/Drawdown 10 best Hyperoptimization Index 4",col="black",type="p",major.ticks="auto",format.labels="%b-%Y")
lines(index_1_tenbest_year[,4]*100,lwd=2,col="green",type="p")
addLegend("topleft", on=1, legend.names = c("Sharpe ", "MaxDrawdown * 100 "), lty=c(1, 1), lwd=c(2, 2),col=c("black","green"))

```
```{r, chap3.2.4.1.13, echo=FALSE, fig.cap="Hyperoptimization 10 best Index 4", include=T,fig.keep = 'last',fig.dim=c(16, 7.1),out.width = "100%"}
################## lengths
plot(index_4_tenbest_year[,2],type="p",col= "red",main= "Filterlengths 10 best Hyperoptimization Index 4 ",ylim=c(-10,260),format.labels="%b-%Y")
lines(index_4_tenbest_year[,3], col=c("coral"),lwd=2,type="p")
lines(index_4_tenbest_year[,5], col=c("blue"),lwd=2,type="p")
lines(index_4_tenbest_year[,6], col=c("cornflowerblue"),lwd=2,type="p")
lines(index_4_onebest_year[,c(2,3,5,6)],type="p",pch=3,lwd= 3,cex=2 ,col= c("red","coral","blue","cornflowerblue"))

addLegend("left", on=1, legend.names = c("long filter sharpe", "long filter drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("coral","cornflowerblue"))
addLegend("bottomleft", on=1, legend.names = c("short filter sharpe", "short filter Drawdown "), lty=c(1, 1), lwd=c(1, 1),col=c("red","blue"))
addLegend("topright", on=1, legend.names = c("maximum values"), pch=3,col="black")

```